server:
  port: 9000

spring:
  config:
    activate:
      on-profile: prod

  sql:
    init:
      platform: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cd0wjlhvqle3.ap-northeast-2.rds.amazonaws.com:3306/dana_db?useSSL=FALSE
    username: dana
    password: ocean628

---

server:
  port: 9001

spring:
  config:
    activate:
      on-profile: test

  sql:
    init:
      platform: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cd0wjlhvqle3.ap-northeast-2.rds.amazonaws.com:3306/dana_db?useSSL=FALSE
    username: dana
    password: ocean628
